A11yance/aria-query

src/index.js

After cloning the repo, I was unable to `npm t` due to a
`flow/no-types-missing-file-annotation` violation in src/index.js

Add flow annotation to index

---

scripts/roles.json

`aria-modal` was added in 1.1 and can be found here: https://www.w3.org/TR/wai-aria-1.1/#aria-modal
I think this is all that needed to be added, but let me know. :)
Ran into this because of an error using eslint-plugin-jsx-a11y when implementing a modal component.

Add `aria-modal` attribute

---

src/ariaPropsMap.js

According to [spec](https://www.w3.org/TR/wai-aria-1.1/#aria-haspopup), `aria-haspopup` takes in more than just boolean values.

Allow Multiple Values Of aria-haspopup

---

src/etc/roles/literal/regionRole.js

I'm working on accesibility project and im using aria-query as a charm. But now html5 frame is deprecated and `<section>` is the new role=region related tag

frame tag is deprecated in html5, should add support to section tag

---

package.json

* `commander` is only used in `scripts/` which aren't published
* couldn't find any reference to `ast-types-flow`

chore: (Re)move unused dependencies

---

README.md

Usage included properties that are not available (`interactive`) or had the incorrect type (`props`, `requiredProps`)

docs(readme): Update roles example

---

.babelrc
.eslintrc
package.json

Currently some of the syntax used results in transpiled code that assumes ES6 Symbol:
https://unpkg.com/aria-query@3.0.0/lib/elementRoleMap.js (see `_slicedToArray`)
This is currently [an abandoned issue in babel](https://github.com/babel/babel/pull/8947)  that is solvable by using `@babel/plugin-transform-runtime` with the `corejs` option. This will over transpile most of the features but I assumed that bundle size is of little concern for this package right now. The most popular dependents are generally dev dependencies (`eslint-plugin-a11y` and `@testing-library/dom`). Over transpiling should be fixed once https://github.com/babel/babel/issues/10008 is done.
To avoid digging through older documentation I just went ahead and upgrade babel to the latest version (which subsequently …

fix: Remove Symbol usage for older environments

---

__tests__/src/ariaPropsMaps-test.js
__tests__/src/rolesMap-test.js

Add double-check ensure that
- role definitions use only props defined by props definitions
- props are used in one or more role definitions
See https://github.com/A11yance/aria-query/issues/18
This PR is depends https://github.com/A11yance/aria-query/pull/20 and https://github.com/A11yance/aria-query/pull/21

Add double-check tests

---

flow/aria.js
scripts/roles.json
src/etc/roles/literal/comboboxRole.js
src/etc/roles/literal/textboxRole.js

Using https://www.w3.org/TR/html-aria/#el-input-file
1. Fix HTML mappings for the `textbox` and `combobox` roles.

Fix HTML relatedConcepts for textbox and combobox

---

package.json

A Peer Dependency to ESLint is not required by this module.

Remove Peer Dependency to ESLint

---

src/etc/roles/literal/textboxRole.js

Fixes `<input>` not being considered a `textbox`.
> The missing value default and the invalid value default are the Text state.
-- https://html.spec.whatwg.org/multipage/input.html#attr-input-type

 fix: input type is text by default

---

.travis.yml
scripts/roles.json

Follow-up on #42 where I forgot to update `roles.json`. 
First commit introduces a CI check. The PR should initially fail (Update: fails as expected https://travis-ci.org/github/A11yance/aria-query/jobs/697547130#L485). After I update roles.json it should pass.

test: Verify that role.json is synced

---

.travis.yml

We only support `node >= 6` anyway according to our `package.json`. It's therefore unnecessary to run travis in node < 6

test: Narrow test matrix

---

scripts/roles.json
src/etc/roles/literal/headingRole.js
src/etc/roles/literal/treeitemRole.js

1. fix: `treeitem` now correctly requires `aria-selected` (https://www.w3.org/TR/wai-aria-1.2/#treeitem).
2. fix: `heading` default value for `aria-level` is stringified `2`.
This is consistent with existing default values.
3. chore(roles.json): `heading` default value for `aria-level` is now included in `props` as well.
Previously was only included in `requiredProps`
The issue was that the working drafts can list required attributes in two forms:
1. in the `Required States and Properties:` row 
2. with `(required)` text if the attribute is inherited
I previously only parsed 1.

fix: Normalize required props

---

README.md
scripts/roles.json
src/etc/roles/literal/definitionRole.js
src/etc/roles/literal/termRole.js

Regarding the issue on [`@testing-library/dom`](https://github.com/testing-library/dom-testing-library/issues/703), I have noticed that `term` and `definition` were not correct

fix: definition/term roles

---

.github/dependabot.yaml
.github/workflows/test.yml

Once #76 lands, you'll have the CI testing back so it should be safe to let dependabot try and update the dependencies through PRs. The filter on the branch is so that it would "double build" for the PR + the branch

chore: Add Depependabot config

---

.npmrc

Looks like package-lock.json is being used now

chore: Remove npmrc

---

flow/aria.js

See reproduction at https://codesandbox.io/s/tender-shannon-q0gki?file=/index.html

fix: type sig for ARIAPropertyDefinition

---

.github/workflows/test.yml

Otherwise changes to package-lock.json will fail the CI check when Dependabot runs.

Only diff the src dir in the CI Diff check

---

package.json

Fails on Windows, not sure what it was supposed to be handling

fix: Remove bash-like command in flow NPM script

---

.eslintignore

Previously, when you would build this package, the build output
would live in `lib/`. However, `eslint` was configured to lint
all files in this package, which would include `lib/`. It would
then start to throw all kinds of warnings about the build output,
which we are not interested in.
Now, we ignore the build output as well as `node_modules` and
generated `reports/`. As such, running `npm run build && npm run lint`
will now pass as expected.

test: Ignore build output when linting

---

.github/workflows/test.yml

Unpin to the latest major v2 versions of the actions to reduce Dependabot noise.
setup-node now has built-in caching, so the the custom setup can be removed

chore: use built-in caching with latest v2 actions

---

package-lock.json
package.json

@eps1lon I think it's OK to remove this dependency. 
1. It's not referenced anywhere
1. `grep -e '@babel/plugin-transform-runtime' -r {src,__tests__,scripts,\.*,package.json}` 
2. The project builds just find without it
Do you remember why it was added or if you need it for your purposes?

Remove @babel/plugin-transform-runtime dev dependency

---

README.md

Relates to #498
The README links to the "stable" version (aka master branch) of the WAI-ARIA 1.3 specification. This PR updates the README to reflect the current direction of the repo stated in #498 to track WAI-ARIA 1.2.
---
As an aside fixes issue with codesandbox configuration.

docs: update README to link to WAI-ARIA 1.2 spec

---

__tests__/src/elementRoleMap-test.js
__tests__/src/roleElementMap-test.js
flow/aria.js
package-lock.json
package.json
scripts/roles.json
src/etc/roles/abstract/sectionRole.js
src/etc/roles/literal/comboboxRole.js
src/etc/roles/literal/complementaryRole.js
src/etc/roles/literal/formRole.js
src/etc/roles/literal/gridcellRole.js
src/etc/roles/literal/imgRole.js
src/etc/roles/literal/linkRole.js
src/etc/roles/literal/listboxRole.js
src/etc/roles/literal/menuitemRole.js
src/etc/roles/literal/progressbarRole.js
src/etc/roles/literal/regionRole.js
src/etc/roles/literal/searchboxRole.js
src/etc/roles/literal/switchRole.js
src/etc/roles/literal/textboxRole.js

Fixes #511 
Fixes #512 
Relates to https://github.com/testing-library/dom-testing-library/issues/1239
**Description**
#447 brought in a number of breaking changes to this repo and was released under a minor version, namely:
1. Removal of the `constraints` array within related concepts `attributes`.
2. Additions / updates according to the unstable [W3C Working Draft for HTML-AAM](https://www.w3.org/TR/html-aam-1.0/).
This PR looks to partially revert some of these changes (with a few other unrelated corrections and additions) to provide an upgrade path to downstream packages, using the following as references:
- https://www.w3.org/TR/html-aria/#docconformance
- https://www.w3.org/TR/wai-aria-1.2/#role_definitions
- https://www.w3.org/TR/html-aam-1.0/#html-element-role-mappings
- …

fix: amend breaking changes and reinstate constraints

---

flow/dequal.js
package-lock.json
package.json
src/elementRoleMap.js

These two changes combined remove the need to pull in the dependency to the project.
This PR is inspired by the work done in https://github.com/A11yance/axobject-query/pull/357 and https://github.com/A11yance/axobject-query/pull/354
As an interesting finding when walking through the code to remove this dependency I discovered(in 431ad2822d1d922825f11840504e1d07b4349afc) that the prior code-path utilizing dequal was impossible (always false situation)
Specifically we were doing a comparison between 
```flow
type ElementARIARoleRelationTuple = [ARIARoleRelationConcept, RoleSet]
```
and
```
type ARIARoleRelationConcept = {|
....
|};
```
Which given the definition of a flow typed union means that these two types have NO overlap.

Remove dequal from the project

---

__tests__/src/elementRoleMap-test.js
package-lock.json
src/elementRoleMap.js

As discovered in https://github.com/A11yance/aria-query/pull/554
Address the defect introduced  https://github.com/A11yance/aria-query/commit/f7f6120770088f7259c38d8a99e629290c343abc#r143856081 
This now exercises all of the code:
Yet now multiple tests are failing in a fixture file used for testing that has been updated since this defect was introduced. I am not sure what the correct state of these fixtures should be

Fix defect in calling code when building the ElementRoleMap

---

.github/dependabot.yaml

@ljharb feel free to close this, but I saw you having to manage a bunch of dependabot PRs and thought this might be helpful
It configures dependabot to only send updates for major versions so that things are kept up-to-date without getting a bunch of PRs that don't meaningfully change anything. Note that the limitations on version updates applied here don't apply to security updates, which are separately managed by dependabot

[chore] reduce dependabot noise

---

__tests__/src/elementRoleMap-test.js
__tests__/src/roleElementMap-test.js
scripts/roles.json
src/etc/roles/graphics/graphicsDocumentRole.js

Fixes #181 
Supports https://github.com/testing-library/dom-testing-library/issues/1295
See relevant specifications:
- https://www.w3.org/TR/html-aria/#docconformance
- https://www.w3.org/TR/svg-aam-1.0/#details-id-66
- https://www.w3.org/TR/html-aam-1.0/#el-svg
Does not address other element role mappings laid out in SVG-AAM.

[New] add implicit role of `graphics-document` to `svg` element

---

__tests__/src/elementRoleMap-test.js
__tests__/src/roleElementMap-test.js
scripts/roles.json
src/etc/roles/literal/deletionRole.js
src/etc/roles/literal/genericRole.js
src/etc/roles/literal/groupRole.js
src/etc/roles/literal/searchRole.js

Resolves #553
The mappings for `hgroup`, `s`, and `search` elements are missing or are incorrect/outdated.
This updates as so:
- `hgroup` element is now associated with the `group` role and no longer associated with the `generic` role.
- `s` element is now associated with the `deletion` role.
- `search` element is now associated with the `search` role.
Relevant specs:
- https://www.w3.org/TR/html-aam-1.0/#el-hgroup
- https://www.w3.org/TR/html-aam-1.0/#el-s
- https://www.w3.org/TR/html-aam-1.0/#el-search
See also [Web Platform Tests for HTML-AAM roles](https://github.com/web-platform-tests/wpt/blob/master/html-aam/roles.html).

[New] update element role mappings
